Repository nbcamp-ch5-team3/project-word-pallete, pull requests merged in 2025-05, with the labels that each got.

#7 [Feat] #1 - learning records UI
  .gitignore
  WordPalette/WordPalette/Domain/UseCase/StudyHistoryUseCase.swift
  WordPalette/WordPalette/Presentation/MyStudy/Components/PaddingLabel.swift
  WordPalette/WordPalette/Presentation/MyStudy/Protocol/UIViewGuide.swift
  WordPalette/WordPalette/Presentation/MyStudy/View/ProfileSectionView.swift
  WordPalette/WordPalette/Presentation/MyStudy/View/StudyHistoryView.swift
  WordPalette/WordPalette/Presentation/MyStudy/ViewController/StudyHistoryViewController.swift
  WordPalette/WordPalette/Presentation/MyStudy/ViewModel/StudyHistoryViewModel.swift
Labels: ✨Feature

#11 [Feat] #3 - 코어데이터 설계 및 코어데이터 매니저와 레포지토리 구현
  WordPalette/WordPalette/App/AppDelegate.swift
  WordPalette/WordPalette/Data/CoreData/CoreDataManager.swift
  WordPalette/WordPalette/Data/CoreData/Object/SolvedWordObject+CoreDataClass.swift
  WordPalette/WordPalette/Data/CoreData/Object/SolvedWordObject+CoreDataProperties.swift
  WordPalette/WordPalette/Data/CoreData/Object/StudyObject+CoreDataClass.swift
  WordPalette/WordPalette/Data/CoreData/Object/StudyObject+CoreDataProperties.swift
  WordPalette/WordPalette/Data/CoreData/Object/UnsolvedWordObject+CoreDataClass.swift
  WordPalette/WordPalette/Data/CoreData/Object/UnsolvedWordObject+CoreDataProperties.swift
  WordPalette/WordPalette/Data/CoreData/Object/UserObject+CoreDataClass.swift
  WordPalette/WordPalette/Data/CoreData/Object/UserObject+CoreDataProperties.swift
  WordPalette/WordPalette/Data/CoreData/WordPalette.xcdatamodeld/WordPalette.xcdatamodel/contents
  WordPalette/WordPalette/Data/RepositoryImpl/RepositoryImplEmpty.swift
  WordPalette/WordPalette/Data/RepositoryImpl/SolvedWordRepositoryImpl.swift
  WordPalette/WordPalette/Data/RepositoryImpl/UserRepositoryImpl.swift
  WordPalette/WordPalette/Domain/Entity/Empty.swift
  WordPalette/WordPalette/Domain/Entity/StudyHistory.swift
  WordPalette/WordPalette/Domain/Entity/UserData.swift
  WordPalette/WordPalette/Domain/Repository/RepositoryEmpty.swift
  WordPalette/WordPalette/Domain/Repository/SolvedWordRepository.swift
  WordPalette/WordPalette/Domain/Repository/UserRepository.swift
Labels: ✨Feature

#15 [Feat] #12 - UnsolvedWordRepository 추가 작업 및 테스트 코드 작성
  WordPalette/WordPalette/Data/CoreData/CoreDataManager.swift
  WordPalette/WordPalette/Data/CoreData/WordPalette.xcdatamodeld/WordPalette.xcdatamodel/contents
  WordPalette/WordPalette/Data/RepositoryImpl/SolvedWordRepositoryImpl.swift
  WordPalette/WordPalette/Data/RepositoryImpl/UnsolvedWordRepositoryImpl.swift
  WordPalette/WordPalette/Data/RepositoryImpl/WordRepositoryImpl.swift
  WordPalette/WordPalette/Domain/Repository/UnsolvedWordRepository.swift
  WordPalette/WordPalette/Domain/Repository/WordRepository.swift
  WordPalette/WordPaletteTests/CoreDataManagerTests.swift
  WordPalette/WordPaletteTests/Mock/MockWordEntity.swift
  WordPalette/WordPaletteTests/Mock/MockWordLocalDataSource.swift
  WordPalette/WordPaletteTests/SolvedWordRepositoryImplTests.swift
  WordPalette/WordPaletteTests/UnsolvedWordRepositoryImplTests.swift
  WordPalette/WordPaletteTests/UserRepositoryImplTests.swift
Labels: ✨Feature

#19 Feature/#6 home view UI
  WordPalette/WordPalette/Presentation/Home/HomeViewController.swift
  WordPalette/WordPalette/Presentation/Home/ViewController/HomeView.swift
  WordPalette/WordPalette/Presentation/Home/ViewController/HomeViewController.swift
  WordPalette/WordPalette/Presentation/Home/ViewController/LevelButtonView.swift
Labels: ✨Feature

#21 [Feat] #16 - 퀴즈 화면 기본 UI 구성
  WordPalette/WordPalette/Presentation/Quiz/Components/QuizStatusView.swift
  WordPalette/WordPalette/Presentation/Quiz/Components/WordCardView.swift
  WordPalette/WordPalette/Presentation/Quiz/QuizView.swift
  WordPalette/WordPalette/Presentation/Quiz/QuizViewController.swift
Labels: ✨Feature

#24 [Feature] - #14 study binding
  WordPalette/WordPalette/Domain/UseCase/StudyHistoryUseCase.swift
  WordPalette/WordPalette/Presentation/MyStudy/Cell/StudyWordCell.swift
  WordPalette/WordPalette/Presentation/MyStudy/Utils/Extension/Extenaion+Date.swift
  WordPalette/WordPalette/Presentation/MyStudy/Utils/Extension/Extension+Level.swift
  WordPalette/WordPalette/Presentation/MyStudy/Utils/Mock/UserDataMock.swift
  WordPalette/WordPalette/Presentation/MyStudy/Utils/Mock/WordEntityMock.swift
  WordPalette/WordPalette/Presentation/MyStudy/Utils/Protocol/UIViewGuide.swift
  WordPalette/WordPalette/Presentation/MyStudy/Utils/Protocol/ViewModelType.swift
  WordPalette/WordPalette/Presentation/MyStudy/Utils/Type/TierType.swift
  WordPalette/WordPalette/Presentation/MyStudy/View/ProfileSectionView.swift
  WordPalette/WordPalette/Presentation/MyStudy/View/StudyHistoryView.swift
  WordPalette/WordPalette/Presentation/MyStudy/View/StudyStatisticsView.swift
  WordPalette/WordPalette/Presentation/MyStudy/ViewController/StudyHistoryViewController.swift
  WordPalette/WordPalette/Presentation/MyStudy/ViewController/StudyStatisticsViewController.swift
  WordPalette/WordPalette/Presentation/MyStudy/ViewModel/StudyHistoryViewModel.swift
  WordPalette/WordPalette/Presentation/MyStudy/ViewModel/StudyStatisticsViewModel.swift
Labels: ✨Feature

#26 [Feature] - #25 di container
  WordPalette/WordPalette/App/DIContainer/DIContainer.swift
  WordPalette/WordPalette/App/SceneDelegate.swift
  WordPalette/WordPalette/Domain/Type/TierType.swift
  WordPalette/WordPalette/Domain/UseCase/StudyHistoryUseCase/StudyHistoryUseCase.swift
  WordPalette/WordPalette/Domain/UseCase/StudyHistoryUseCase/StudyHistoryUseCaseImpl.swift
  WordPalette/WordPalette/Presentation/MyStudy/View/StudyHistoryView.swift
  WordPalette/WordPalette/Presentation/MyStudy/ViewController/StudyHistoryViewController.swift
  WordPalette/WordPalette/Presentation/Shared/Components/PaddingLabel.swift
  WordPalette/WordPalette/Presentation/Shared/Components/StatLabel.swift
  WordPalette/WordPalette/Presentation/Shared/Extension/Extenaion+Date.swift
  WordPalette/WordPalette/Presentation/Shared/Extension/Extension+Level.swift
Labels: 👍Enhance, ✨Feature

#27 [Feat] /#23 - 카드 스와이프 애니메이션 및 ViewModel 바인딩 구조 설계
  WordPalette/WordPalette/App/DIContainer/DIContainer.swift
  WordPalette/WordPalette/Presentation/Quiz/Components/QuizCardStackView.swift
  WordPalette/WordPalette/Presentation/Quiz/Components/QuizCardView.swift
  WordPalette/WordPalette/Presentation/Quiz/Components/QuizStatusView.swift
  WordPalette/WordPalette/Presentation/Quiz/Model/QuizViewInfo.swift
  WordPalette/WordPalette/Presentation/Quiz/QuizView.swift
  WordPalette/WordPalette/Presentation/Quiz/QuizViewController.swift
  WordPalette/WordPalette/Presentation/Quiz/QuizViewModel.swift
Labels: ✨Feature

#36 [Feat] #29 - QuizUseCase구현 및 코어데이터 로직 수정
  WordPalette/WordPalette/App/DIContainer/DIContainer.swift
  WordPalette/WordPalette/Data/CoreData/CoreDataErrorType.swift
  WordPalette/WordPalette/Data/CoreData/CoreDataManager.swift
  WordPalette/WordPalette/Data/CoreData/CoreDataStack.swift
  WordPalette/WordPalette/Data/CoreData/TestCoreDataStack.swift
  WordPalette/WordPalette/Data/RepositoryImpl/SolvedWordRepositoryImpl.swift
  WordPalette/WordPalette/Domain/Repository/SolvedWordRepository.swift
  WordPalette/WordPalette/Domain/UseCase/QuizUseCase/QuizUseCase.swift
  WordPalette/WordPalette/Domain/UseCase/QuizUseCase/QuizUseCaseImpl.swift
  WordPalette/WordPalette/Presentation/Quiz/Components/QuizCardStackView.swift
  WordPalette/WordPalette/Presentation/Quiz/Components/QuizCardView.swift
  WordPalette/WordPalette/Presentation/Quiz/QuizView.swift
  WordPalette/WordPalette/Presentation/Quiz/QuizViewController.swift
  WordPalette/WordPalette/Presentation/Quiz/QuizViewModel.swift
Labels: 🐛BugFix, ✨Feature

#42 [Fix] - #39 bugfix statistics
  WordPalette/WordPalette/Domain/UseCase/StudyHistoryUseCase/StudyHistoryUseCaseImpl.swift
  WordPalette/WordPalette/Presentation/MyStudy/Cell/StudyWordCell.swift
  WordPalette/WordPalette/Presentation/MyStudy/View/StudyStatisticsView.swift
  WordPalette/WordPalette/Presentation/MyStudy/ViewController/StudyHistoryViewController.swift
  WordPalette/WordPalette/Presentation/MyStudy/ViewController/StudyStatisticsViewController.swift
  WordPalette/WordPalette/Presentation/MyStudy/ViewModel/StudyStatisticsViewModel.swift
Labels: 🐛BugFix, 👍Enhance
